fix: add pr results job to stop renovate pushing broken pr

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -33,7 +33,7 @@ jobs:
     with:
       environment_name: tools
       command: plan
-      tag: ${{ github.event.number || 'latest' }} 
+      tag: ${{ github.event.number || 'latest' }}
       app_env: ${{ github.event.number || 'latest' }} # ephermal, prefixed for easy clean up of PR resources in s3 and dynamodb generated by terraform
     secrets: inherit
   lint:
@@ -66,7 +66,6 @@ jobs:
       - name: Run TFLint
         run: tflint --recursive -f compact
 
- 
   deploy-to-tools:
     name: Deploy to Tools
     #needs: builds
@@ -82,3 +81,12 @@ jobs:
       app_env: tools
     secrets: inherit
 
+  results:
+    name: PR Results
+    needs: [builds, plan-stack, lint]
+    if: always()
+    runs-on: ubuntu-slim
+    steps:
+      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
+        run: echo "At least one job has failed." && exit 1
+      - run: echo "Success!"
